name: cicd-pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  gitleaks:
    name: secrets-scanning
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: install gitleaks
        run: sudo apt update && sudo apt install gitleaks
      - name: scan for secrets
        run: gitleaks detect --source . --verbose
  sca:
    name: dependency check
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v7
      - name: setup node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - name: install dependencies
        run: npm ci
      - name: scan dependencies
        run: npm audit --audit-level=high || true

