name: cicd-pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  gitleaks:
    name: secrets-scanning
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: install gitleaks
        run: sudo apt update && sudo apt install gitleaks
      - name: scan for secrets
        run: gitleaks detect --source . --verbose
  sca:
    name: dependency check
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v7
      - name: setup node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - name: install dependencies
        run: npm ci --ignore-scripts
      - name: scan dependencies
        run: npm audit --audit-level=high || true
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0 
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  lint:
    name: lint-test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v7
      - name: setup node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - name: install dependencies
        run: npm ci --ignore-scripts
      - name: lint test
        run: npm run lint
  build:
    needs: [gitleaks,sca,sonarqube,lint]
    runs-on: ubuntu-latest
    steps:
      - name: setup repo
        uses: actions/checkout@v7
      - name: setup node
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - name: install dependencies
        run: npm ci --ignore-scripts
      - name: build app
        run: npm run build